# Generated by Django 4.0.4 on 2022-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=64)),
                ('host_organisation', models.CharField(max_length=64)),
                ('start_date', models.CharField(max_length=64)),
                ('end_date', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('organisation', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('account_type', models.CharField(max_length=15)),
            ],
        ),
    ]
