# Generated by Django 4.0.4 on 2022-04-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='submitter_name',
            new_name='submitter_email',
        ),
    ]
